name: Piki7

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
        env:
          CI: true
      - name: Initialize Google Cloud SDK & Deploy
        uses: google-github-actions/setup-gcloud@master
        with:
          gae_config_path: '../app.yaml'
          service_account: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}